# docker-compose.yml
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      DEV_MODE: "${DEV_MODE}"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      bash -c "
        # python -u scripts/populate_db.py &&

        if [ \"$${DEV_MODE}\" = \"true\" ]; then
          uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload;
        else
          uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 2;
        fi
      "

volumes:
  postgres_data: