[tool.black]
line-length = 88
exclude = '''
/(
    \.venv
  | env
  | data
  | notebooks
  | tests
)/
'''

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
exclude = [
    ".venv",
    "env",
    "data",
    "notebooks",
]